name = "be"
compatibility_date = "2023-12-01"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzkyYmM5ZGMtOWJjOC00MTRhLWE2NzEtODg2NmY5ZDEwNjg3IiwidGVuYW50X2lkIjoiYmRiNzZhYmFhM2IxMmFiNTRkOWI1M2IyYTUxNGMzMjkyOGU5ZDQyOTcyMTU3M2IwMTNkMjAzZDQ4NDUzYjdkZCIsImludGVybmFsX3NlY3JldCI6IjdhMmM5OWViLWE4MDItNDM4MC1iNTNiLTI4ZDc1M2ExMmU3ZCJ9.Elo7KOh_WIYWhBN-5nRpxV8RBWhyBLgUMKmsRRdIb2U"
JWT_SECRET = "here:is:my:jwt:secret"
# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
